// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWc2tLFOhRPAiNf63lRgk6jOXeQ6zKLn0',
    appId: '1:11530836983:web:a6bca907efd96afc03ecf2',
    messagingSenderId: '11530836983',
    projectId: 'jawda-b97b3',
    authDomain: 'jawda-b97b3.firebaseapp.com',
    storageBucket: 'jawda-b97b3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQzQqXaNQHe293IJZ1aPkVaZN1mjsf_To',
    appId: '1:11530836983:android:a26f72025419f20203ecf2',
    messagingSenderId: '11530836983',
    projectId: 'jawda-b97b3',
    storageBucket: 'jawda-b97b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH9yG7UkcBdntcoJ1SeDa8KtssSWFo5T4',
    appId: '1:11530836983:ios:c11e9dc5fccf31da03ecf2',
    messagingSenderId: '11530836983',
    projectId: 'jawda-b97b3',
    storageBucket: 'jawda-b97b3.firebasestorage.app',
    iosBundleId: 'com.example.jawda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH9yG7UkcBdntcoJ1SeDa8KtssSWFo5T4',
    appId: '1:11530836983:ios:c11e9dc5fccf31da03ecf2',
    messagingSenderId: '11530836983',
    projectId: 'jawda-b97b3',
    storageBucket: 'jawda-b97b3.firebasestorage.app',
    iosBundleId: 'com.example.jawda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWc2tLFOhRPAiNf63lRgk6jOXeQ6zKLn0',
    appId: '1:11530836983:web:3fcc77ff8623236c03ecf2',
    messagingSenderId: '11530836983',
    projectId: 'jawda-b97b3',
    authDomain: 'jawda-b97b3.firebaseapp.com',
    storageBucket: 'jawda-b97b3.firebasestorage.app',
  );
}
